#!/bin/bash

PANDA_BUILD=/opt/panda/build/
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo "booting ..."
$PANDA_BUILD/i386-softmmu/qemu-system-i386 -hda $DIR/OS/wheezy_panda2.qcow2 -m 3500 -net nic -net user -monitor stdio

